### ISSUE TITLE
[Question] "Additional Authenticated Data" ?

### ISSUE THREAD

**Issue by Noschvie** [metrophos/LoxBerry-Plugin-P1-Decrypter#3]
Wofür wird "Additional Authenticated Data" verwendet bzw. wofür ist diese Feld notwendig ?

**Comment by Noschvie** [comment]
Das Feld "Additional Authenticated Data" ist für netz-noe nicht erforderlich.

**Comment by metrophos** [comment]
Hi!
Laut meinen Recherchen könnten die "Additional Authenticated Data" vom Netzanbietern zusätzlich zur Verschlüsselung der Daten genutzt werden, dadurch würden diese auch in den Einstellungen erforderlich werden. Ich habe dies noch nicht gesehen aber deshalb die Option integriert falls es mal bei jemanden nötig werden sollte.
